#!/usr/bin/env bash

set -euxo pipefail

# Checkout dawn submodule
if [[ ! -d "dawn" ]] || ! find dawn -mindepth 1 -maxdepth 1 | read; then
    git submodule update --init
fi

pushd dawn

# Bootstrap gclient config if it doesn't exist
if [[ ! -f ".gclient" ]]; then
    cp scripts/standalone.gclient .gclient
fi

# Fetch dawn dependencies
gclient sync

popd

mkdir -p build
cd build

cmake_args=(
    "-GNinja"
    "-DCMAKE_BUILD_TYPE=Release"
    "-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=$(pwd)/lib"
    "-DTINT_BUILD_HLSL_WRITER=ON"
    "-DTINT_BUILD_MSL_WRITER=ON"
    "-DTINT_BUILD_SPV_WRITER=ON"
)

if [[ -n "${LLVM_NATIVE_TOOLCHAIN-}" ]]; then
    cmake_args+=("-DLLVM_NATIVE_TOOLCHAIN=$LLVM_NATIVE_TOOLCHAIN")
fi

if [[ -n "${XWIN_CACHE-}" ]]; then
    cmake_args+=("-DXWIN_CACHE=$XWIN_CACHE")
fi

san_cflags=""
san_ldflags=""

if [[ "${ENABLE_SANITIZERS:-0}" == "1" ]]; then
    export CC="${CC:-clang}"
    export CXX="${CXX:-clang++}"

    cmake_args+=("-DDAWN_ENABLE_ASAN=ON" "-DDAWN_ENABLE_UBSAN=ON")
    san_cflags="-fsanitize=address -fsanitize=undefined"
    
    if [[ -n "${LLVM_NATIVE_TOOLCHAIN-}" ]]; then
        # For MSVC cross-compilation, configure linking paths directly
        clang_bin="$LLVM_NATIVE_TOOLCHAIN/bin/clang"
        resource_dir=$("$clang_bin" -print-resource-dir)
        win_lib_dir="$resource_dir/lib/windows"
        
        san_ldflags="-libpath:$win_lib_dir clang_rt.asan_dynamic-x86_64.lib clang_rt.asan_dynamic_runtime_thunk-x86_64.lib -include:__asan_seh_interceptor -wholearchive:clang_rt.asan_dynamic_runtime_thunk-x86_64.lib clang_rt.ubsan_standalone-x86_64.lib -nodefaultlib:stl_asan.lib -nodefaultlib:vcasan.lib -D_HAS_ASAN=0"
        
        cmake_args+=("-DCMAKE_TRY_COMPILE_CONFIGURATION=Release")
    else
        # For native compilations, apply the sanitizer flags as CMake globals
        cmake_args+=("-DCMAKE_C_FLAGS=$san_cflags" "-DCMAKE_CXX_FLAGS=$san_cflags")
    fi
fi

export CFLAGS="$san_cflags"
export CXXFLAGS="-Wno-float-equal $san_cflags"

if [[ -n "$san_ldflags" ]]; then
    export LDFLAGS="$san_ldflags"
fi

cmake_args+=("$@")

cmake "${cmake_args[@]}" ../dawn
build_targets=(
    "dawn_native"
    "dawn_proc"
    "webgpu_dawn"
    "tint_api"
)

if [[ "${TARGET_OS:-}" != "ios" ]]; then
    build_targets+=("tint_cmd_tint_cmd")
fi

cmake --build . --target "${build_targets[@]}"
